trigger:
  - master

pr: none

variables:
  is_release: false

stages:
  - stage: 'notebook_tests'
    displayName: 'notebook tests'

    jobs:
      - job: 'test_notebooks'
        displayName: 'test notebooks linux'
        timeoutInMinutes: 30
        pool:
          vmImage: 'ubuntu-18.04'
        variables:
          test_output: 'notebooks.xml'
        steps:
          - template: test_notebooks_and_publish_results.yml
  - stage: 'make_sphinx_documentation'
    displayName: 'make sphinx documentation'

    jobs:
      - template: documentation_build.yml
  - stage: "deploy_documentation"
    displayName: "deploy documentation"

    jobs:
      - template: documentation_deploy.yml
