trigger:
  - master

pr: none

stages:
  - stage: 'notebook_tests'
    displayName: 'notebook tests'

    jobs:
      - job: 'imaging_notebook_linux'
        displayName: 'bragg-edge imaging notebook linux'
        timeoutInMinutes: 30
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          - bash: |
             set -ex
             conda config --set always_yes yes --set changeps1 no
             conda env create -f ess-notebook-latest.yml
             source activate ess-notebook-latest
             git clone https://github.com/scipp/ess-notebooks-data.git data
             python make_config.py ${PWD}/data
             mkdir tests
             cp scippconfig.py tests/
             find . -not -path "*/\.*" -type f -name "*.ipynb"\
              | xargs jupyter nbconvert --to python --output-dir tests\
              --RegexRemovePreprocessor.patterns="['^# exclude-from-export']"
             find tests -not -path "tests/scippconfig.py" -type f -name "*.py" | xargs python
  - stage: 'make_sphinx_documentation'
    displayName: 'make sphinx documentation'

    jobs:
      - template: documentation_build.yml
  - stage: "deploy_documentation"
    displayName: "deploy documentation"

    jobs:
      - template: documentation_deploy.yml
