trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_release: $[eq(variables['System.PullRequest.TargetBranch'], 'release')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:
  - stage: 'notebook_tests'
    displayName: 'notebook tests'

    jobs:
      - template: test_notebooks.yml
