trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_release: $[eq(variables['System.PullRequest.TargetBranch'], 'release')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:
  - stage: 'notebook_tests'
    displayName: 'notebook tests'

    jobs:
      - job: 'make_notebooks'
        displayName: 'bragg-edge imaging notebook linux'
        timeoutInMinutes: 30
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          - bash: |
             set -ex
             echo is master $(is_release)
             echo target branch $(System.PullRequest.TargetBranch)
             conda config --set always_yes yes --set changeps1 no
             if [ $(is_release) == False ]; then
                 conda env create -f ess-notebook-latest.yml
                 source activate ess-notebook-latest
                 echo '##vso[task.setvariable variable=conda_env]ess-notebook-latest'
             else
                 conda env create -f ess-notebook.yml
                 source activate ess-notebook
                 echo '##vso[task.setvariable variable=conda_env]ess-notebook'
             fi
            displayName: 'setup conda environment'
          - bash: |
             set -ex
             source activate $(conda_env)
             git clone https://github.com/scipp/ess-notebooks.git notebooks
            displayName: 'clone notebooks'
          - bash: |
             set -ex
             source activate $(conda_env)
             cd notebooks
             git clone https://github.com/scipp/ess-notebooks-data.git data
             python make_config.py ${PWD}/data/ess/v20/imaging
             mkdir tests
             cp scippconfig.py tests/
             find . -not -path "*/\.*" -type f -name "*.ipynb"\
              | xargs jupyter nbconvert --to python --output-dir tests\
              --RegexRemovePreprocessor.patterns="['^# exclude-from-export']"
             find tests -not -path "tests/scippconfig.py" -type f -name "*.py" | xargs python
            displayName: 'execute notebook'
