trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_release: $[eq(variables['System.PullRequest.TargetBranch'], 'release')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:
  - stage: 'notebook_tests'
    displayName: 'notebook tests'

    jobs:
      - job: 'test_notebooks'
        displayName: 'test notebooks linux'
        timeoutInMinutes: 30
        pool:
          vmImage: 'ubuntu-18.04'
        variables:
          test_output: 'notebooks.xml'
        steps:
          - template: test_notebooks_and_publish_results.yml
